### ISSUE TITLE
ERROR: lazy loading failed for package

### ISSUE THREAD

**Issue by niteshshrestha** [SantanderMetGroup/loadeR#17]
COULD YOU PLEASE HELP ON THIS?

devtools::install_github(c("SantanderMetGroup/loadeR.java", "SantanderMetGroup/loadeR"))
Downloading GitHub repo SantanderMetGroup/loadeR.java@master
from URL https://api.github.com/repos/SantanderMetGroup/loadeR.java/zipball/master
Installing loadeR.java
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/nitesh/AppData/Local/Temp/Rtmpgrbu9X/devtools2b785efe7b32/SantanderMetGroup-loadeR.java-14fcdf1"  \
  --library="C:/Users/nitesh/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'loadeR.java' ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error : package 'rJava' could not be loaded
ERROR: lazy loading failed for package 'loadeR.java'
* removing 'C:/Users/nitesh/Documents/R/win-library/3.3/loadeR.java'
Error: Command failed (1)

**Comment by jbedia** [comment]
Hi,

Look at this line of your error message:
```
 No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
```

It seems that Java is not properly installed, or you are using different architectures for java/R (e.g. java 64 bit and R 32 bit, or viceversa).
I hope this helps
