### ISSUE TITLE
ERROR: lazy loading failed for package 'SGAT'

### ISSUE THREAD

**Issue by nperlut** [SantanderMetGroup/loadeR#18]
Hi, I cannot figure this error out.  Some posts suggest uninstalling and reinstalling...which I did twice.  Any thoughts on what is going on?

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\nperlut\AppData\Local\temp\Rtmpuukysf\downloaded_packages
> library(devtools)
> install_github("SWotherspoon/SGAT")
Downloading GitHub repo SWotherspoon/SGAT@master
from URL https://api.github.com/repos/SWotherspoon/SGAT/zipball/master
Installing SGAT
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nperlut/AppData/Local/temp/Rtmpuukysf/devtools1ad4426c5857/SWotherspoon-SGAT-e692815"  \
  --library="C:/Users/nperlut/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'SGAT' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'SGAT'
* removing 'C:/Users/nperlut/Documents/R/win-library/3.3/SGAT'
Error: Command failed (1)

**Comment by jbedia** [comment]
Has this something to do with loadeR?

**Comment by nperlut** [comment]
I am fairly new to R and not familiar with loadeR.  Is that an installation issue with the program?
