### ISSUE TITLE
Error: "class not found"

### ISSUE THREAD

**Issue by bthrasher** [SantanderMetGroup/loadeR#19]
I am experiencing the following error and cannot seem to figure it out:

> library(rJava)
> library(loadeR)
> di <- dataInventory("/Volumes/INDIA/tasmax_day_CCSM4_historical_r1i1p1_1990.nc")
[2017-02-21 14:48:23] Doing inventory ...
**Error in .jfindClass(as.character(class)) : class not found**
> Sys.getenv("JAVA_HOME")
[1] "/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home"

loadeR version 1.0-7 (2017-01-25)
rJava 0.9-8
OSX 10.10.5

Any ideas? Thanks in advance!

**Comment by jbedia** [comment]
Hi, not really sure about what can be wrong... Can you please type 
"library(loadeR)" in a new session and report the messages appearing on 
screen? Thanks
