### ISSUE TITLE
Creating my first NCML

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/loadeR#22]
Hi, I was trying to learn how to create a NCML. I am working with CHIRP file, here a list of sample NetCDF files: https://drive.google.com/open?id=0B6GeSpmxHEuiQklRRFBmVnNPWEU

This is a sample NCML files which — sorry for the spoiler — does not work:
```
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
   <!-- aggregate existing files over the time dimension -->
   <aggregation type="joinExisting" dimName="time">
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.01.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.02.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.03.tif.nc"/>
   </aggregation>
</netcdf>
```
Or better, it works opened with Panoply (that is Java based) but when:
```
> dataInventory('/opt/data/CHIRP/test/CHIRP.ncml')
[2017-04-12 22:40:30] Doing inventory ...
Error: No variables found
```
Ok, I have just realised that a function names `makeAggregatedDataset` exists! Let's try:
```
> makeAggregatedDataset('/opt/data/CHIRP/test/', '/opt/data/CHIRP/test/out.ncml')
[2017-04-12 22:38:23] Creating dataset from 9 files
[2017-04-12 22:38:23] Scanning file 1 out of 1
Error in .jnew(.class.to.jclass[cm], a) : java.lang.NullPointerException
```
Uhm, I don't know what I am doing wrong, can you help me?

**Comment by sixtohg** [comment]
Hi Matteo,
loadeR is based on the netcdf java from unidata. In particular, on the grid object. The problem of the dataInventory function is that there are not grid objects defined in your netcdf files. This is a common problem in the coordinates system definition for each variable. To fix it, the attributes defining the coordinate system of the variables should be included and the dimensions and coordinates should be defined correctly. We have some examples in our trac, https://meteo.unican.es/trac/wiki/NCMLUserStories, that We use to explain how to modify nc-files using ncml. 
Best regards, 
Sixto

**Comment by matteodefelice** [comment]
Thank you for the reply, I have added:
```
 <variable name="rsds" orgName="Band1">
                        <attribute name="_CoordinateAxes" value="time lat lon"/>
                </variable>
```
but still nothing. Then I have realised that `loadGridData` doesn't work even on single files:
```
> d = loadGridData('/opt/data/CHIRP/test/CHIRP.2015.03.tif.nc', 'Band1')
Error: Variable requested not found
Check 'dataInventory' output and/or dictionary 'identifier'.
```
also here `dataInventory` does not work. The strange thing is that panoply, using the same Java librarie, can open those files...

**Comment by sixtohg** [comment]
I hace not used panoply but it seems that it is based not in grids objects but in variables. The nc-file is correctly open by both, panoply and toolsui, java-libraries and both identificy the variables but only panoply is able to plot the map because toolsui, from unidata, needs grid objects to build the map. To identify the problem I need the file or the ncdump description. Without this it is difficult to say WhatsApp is the problem and which are the attributes that should be included.

**Comment by matteodefelice** [comment]
The files are in the Google Drive link I have posted at the beginning. Thank you again,

**Comment by sixtohg** [comment]
Hi Matteo,
sorry but I had the pc at the university and until now I can not see the files. On the one hand, the coordinates are not well defined in your files cause they have not the axis type attribute. This is the reason why you have not grids in your nc-files. This is an example that should work based on your first comment (revise the location of the nc-files):

<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
   <aggregation type="joinExisting" dimName="time">
      <netcdf location="./CHIRP.2015.01.tif.nc"/>
      <netcdf location="./CHIRP.2015.02.tif.nc"/>
      <netcdf location="./CHIRP.2015.03.tif.nc"/>
   </aggregation>
  <variable name="time">
	<attribute name="_CoordinateAxisType" value="Time" />
  </variable>
  <variable name="lon">
	<attribute name="_CoordinateAxisType" value="Lon" />
  </variable>
  <variable name="lat">
	<attribute name="_CoordinateAxisType" value="Lat" />
  </variable>
  <variable name="Band1">
	<attribute name="coordinates" value="time lat lon" />
  </variable>
</netcdf>

**Comment by matteodefelice** [comment]
How can you say that coordinates are not well defined? May I understand it from looking at the `ncdump`? Just to learn for the next times...

**Comment by sixtohg** [comment]
Sorry, I am referring that they don't include all the attributes to be completely defined. In most cases, and for some software, it is enough with the attributes included in your nc-files:
double lon(lon=1500);
  :standard_name = "longitude";
  :long_name = "longitude";
  :units = "degrees_east";
  :axis = "X";

But, for more complex datasets as the included in the UDG-THREDDS server, we can not work only with the object variable because they can co-exists several coordinates system (e.g. different time axis or pressure level coordinates) so we need to use the grid, which is a more complex object including variable and coordinate system. This is the reason why we need some extra attributes, mainly the CoordinateAxisType, for the coordinate variables and coordinates for the variable, although this latest some times is implicitly defined with the dimensions of the variable.
I have seen a problem with the time aggregation of the example I have sent you. Give some minutes to fix it and send you a functional version.

**Comment by sixtohg** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
	<variable name="time">
		<attribute name="_CoordinateAxisType" value="Time" />
		<attribute name="units" value="days since 2015-01-01"/>
		<attribute name="_CoordinateAxisType" value="Time" />
		<values>0 31 59 90 120 151 181 212 243</values>
	</variable>
	<variable name="lon">
		<attribute name="_CoordinateAxisType" value="Lon" />
	</variable>
	<variable name="lat">
		<attribute name="_CoordinateAxisType" value="Lat" />
	</variable>
   <aggregation type="joinExisting" dimName="time">
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.01.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.02.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.03.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.04.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.05.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.06.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.07.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.08.tif.nc"/>
      <netcdf location="/opt/data/CHIRP/test/CHIRP.2015.09.tif.nc"/>
   </aggregation>
</netcdf>

**Comment by matteodefelice** [comment]
Thanks @cofinoa and @sixtohg, I *start* to understand a bit more the whole issue. However, I still don't understand how " to check that the original files are recognized as Grid data fields", what am I supposed to do? Then, it should be possible to put some more check on the `dataInventory` function to have a more useful output in case of errors (like mine)?

I will try to use the NCML you have prepared here to better understand how to deal with this...

**Comment by sixtohg** [comment]
The FeatureTypes option of the toolsUI from UNIDATA
http://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/toolsUI/4.6.8/toolsUI-4.6.8.jar
Lets you know if there is any grid object defined in your file. Without explicitly exploring with the Java methods the nc-file, this is the easiest option, in my opinion.

**Comment by sixtohg** [comment]
This Java-tool also lets you to edit the nc-files, explore and build ncml-files, save the ncml-file as NetCDF (version 3 or 4) and other less commonly used utilities (e.g. work with time-series instead grids).

**Comment by cofinoa** [comment]
@matteodefelice 

A "scan" version of your example. The time coordinate is fully overloaded and a new one is created. 

```
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
   <aggregation type="joinExisting" dimName="time">
      <!-- CHIRP.2015.01.tif.nc -->
      <scan location="./" dateFormatMark="CHIRP.#yyyy.MM" suffix=".tif.nc" subdirs="false"/>
   </aggregation>
</netcdf>
```

**Comment by matteodefelice** [comment]
@cofinoa This scan version needs a single ncml file for each NetCDF to fix the coordinates as you said before?
