### ISSUE TITLE
object 'lf' not found

### ISSUE THREAD

**Issue by gcurci** [SantanderMetGroup/loadeR#23]
I am learning the loadeR and downscaleR packages, but I am experiencing troubles in loading the station data. Following the example on the wiki:

> dir.create("mydirectory")
> download.file("http://meteo.unican.es/work/loadeR/data/VALUE_ECA_86_v2.tar.gz"                                                                                        +               destfile = "mydirectory/VALUE_ECA_86_v2.tar.gz")
trying URL 'http://meteo.unican.es/work/loadeR/data/VALUE_ECA_86_v2.tar.gz'
Content type 'application/x-gzip' length 8457445 bytes (8.1 MB)
==================================================
downloaded 8.1 MB

> untar("mydirectory/VALUE_ECA_86_v2.tar.gz", exdir = "mydirectory")
> value <- "mydirectory/VALUE_ECA_86_v2"
> library(loadeR)
Loading required package: rJava
Loading required package: loadeR.java
Java version 1.7.0_131-mockbuild_2017_02_13_15_19-b00 amd64 by Oracle Corporatio                                                                                        n detected
NetCDF Java Library v4.6.0-SNAPSHOT (23 Apr 2015) loaded and ready
loadeR version 1.0.8 (2017-04-11) is loaded
> valueload <- loadStationData(value, var = "tmean")
**Error: [2017-04-14 00:24:18] Variable requested not found**
> print(sessionInfo())
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8
 [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] loadeR_1.0.8      loadeR.java_1.1-0 rJava_0.9-8

loaded via a namespace (and not attached):
[1] abind_1.4-5    RCurl_1.95-4.8 bitops_1.0-6

> dataInventory("mydirectory/VALUE_ECA_86_v2", return.stats = T)
[2017-04-14 00:27:03] Doing inventory ...
**Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  object 'lf' not found**

I reported all the commands entered, and highlighted in boldface the errors I got, which I suppose come from the same origin. I was not able to traceback() the real cause.

Do you have any hint on that? This error basically prevents the usage of this very nice package, since it is not possible to load obsevations.

Thanks and best wishes,
Gabriele

**Comment by sixtohg** [comment]
Dear Gabriele,

there are two different errors in your code. The second is related with the dataInventory function and, in my opinion, it is related in your case with the path of the dataset. I have used your code and, with the dataset and directory well defined it works fine. The first one is related with the function loadStationData. In this case, I have obtained the same error message and, revising the code of the function, I have seen a possible explanation in the line 153:
fileInd <- grep(paste0("^", var, "\\.txt$"), dirContents)
In this line, the function is not able to find the file corresponding to the requested variable. In my opinion, it should be:
fileInd <- grep(paste0(var, ".txt"), dirContents)

@jbedia could you revise this part of the code?

Best regards,
Sixto

**Comment by gcurci** [comment]
Dear Sixto,

thanks much for your feedback. I thought that the to errors were the same, because the second error pops up only when actually requesting data reading of the variables, i.e. when return.stats = T:

> dataInventory("mydirectory/VALUE_ECA_86_v2")
[2017-04-15 21:32:06] Doing inventory ...
[2017-04-15 21:32:07] Done.
$Stations
$Stations$station_id
 [1] "000012" "000013" "000014" "000015" "000016" "000017" "000021" "000028"
 [9] "000029" "000030" "000032" "000038" "000039" "000042" "000048" "000054"
[17] "000058" "000059" "000062" "000063" "000107" "000113" "000173" "000175"
[25] "000176" "000177" "000190" "000191" "000192" "000194" "000195" "000200"
...

this is successful, while this one:

> dataInventory("mydirectory/VALUE_ECA_86_v2", return.stats = T)
[2017-04-15 21:31:54] Doing inventory ...
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  object 'lf' not found

fails, as previously reported. Moreover, the directory is correctly set in both cases.

Maybe is related to the update of some system library, not sure. I am using Centos 6 (always updated), but I have the same error also with Centos 7 on another server.

Thanks and have a Peaceful Easter!
Gabriele

**Comment by jbedia** [comment]
Hi Gabriele,
I fixed the errors in 27e8076. In case any other problems arise just let us know, thanks for reporting

**Comment by gcurci** [comment]
Hi Joaquin,

thanks a lot! I just installed the fixed version and now it works fine!

Best,
Gabriele
