### ISSUE TITLE
Can loadeR deal with grids other than lat-lon (e.g. lambertian)?

### ISSUE THREAD

**Issue by gcurci** [SantanderMetGroup/loadeR#25]
Hello,
before attempting to process a large dataset, I am trying to figure out if the loadeR, transformeR and downscaleR packages can deal with projections other than regular lat-lon. In my case, I would like to works with Lambertian projection.

Thanks for any hint you may have on that, I was not able to find an answer browsing the wiki and the documentation.

Best regards,
Gabriele Curci

**Comment by jbedia** [comment]
Hi Gabriele. Thanks for your enquiry. Yes, `loadGridData` and other utilities in package transformeR are envisaged to deal with non-regular (rotated) coordinates. In case any problems/questions/suggestions for enhancement arise just let us know. Best regards

**Comment by gcurci** [comment]
Dear Joaquin,

thanks for the response. If any question/suggestion arises when I'll try I will certainly let you know.

Best,
Gabriele
