### ISSUE TITLE
Java versions nightmare

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/loadeR#27]
Hi, yesterday I had to upgrade Java to version 8 on my ubuntu machine. Well, I'm still trying to resurrect the whole loadeR  ecosystem. 
I swichted back to version 7 using `update-alternatives`, reinstalled rJava from sources, did the javareconf from sudo but when: 
```
> devtools::install_github(c("SantanderMetGroup/loadeR.java")
+ )
Downloading GitHub repo SantanderMetGroup/loadeR.java@master
from URL https://api.github.com/repos/SantanderMetGroup/loadeR.java/zipball/master
Installing loadeR.java
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmpOaPnHp/devtools66f254151636/SantanderMetGroup-loadeR.java-14fcdf1'  \
  --library='/home/matteo/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘loadeR.java’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Segmentation fault (core dumped)
ERROR: loading failed
* removing ‘/home/matteo/R/x86_64-pc-linux-gnu-library/3.3/loadeR.java’
Installation failed: Command failed (1)
```
`rJava' seems to work, `.jinit()` doesn't trigger any error and this happens both on Rstudio and on R in the terminal. Any clue?

**Comment by matteodefelice** [comment]
Apparently in 2017 you still have to reboot your system...
after installing rJava from r-forge, adding JAVA_HOME in my conf files, doing javareconf something like 100 times...after the reboot I could install your packages...

**Comment by jbedia** [comment]
Hi Matteo,
I had exactly the same issue last week after java version upgrade (I needed v8 for other applications). I struggled for a while with no success with update-alternatives, and finally came up with the solution after reboot (for a different reason). Thanks for reporting anyway. It may help others in the same situation.

**Comment by cofinoa** [comment]
Matteo and Joaquín, 
Just for the record , could you report  your operating system and version? 

The java update in OSX it's tricky but I would no expect this weird requirement with linux.

If a reboot it's requiered it's because a some cleanup of in memory process had happened

Antonio

**Comment by jbedia** [comment]
Hi both. I have updated the [installation section](https://github.com/SantanderMetGroup/loadeR/wiki/Installation) in the wiki linking this issue. @cofinoa, I am using ubuntu 14.04 64-bit.

**Comment by matteodefelice** [comment]
Ubuntu 17.04 64-bit

**Comment by serignembackecoly** [comment]
Hi everyone,

After a lots of trying and testing I still get this error:

`devtools::install_github(c("SantanderMetGroup/loadeR.java", "SantanderMetGroup/climate4R.UDG", "SantanderMetGroup/loadeR")) Downloading GitHub repo SantanderMetGroup/loadeR.java@HEAD Error in utils::download.file(url, path, method = method, quiet = quiet, : download from 'https://api.github.com/repos/SantanderMetGroup/loadeR.java/tarball/HEAD' failed`

The package climate4R.UDG have been installed well.

Really looking forward to using this package !
