### ISSUE TITLE
"Error in loadingStationData "

### ISSUE THREAD

**Issue by AZIZRIZWAN** [SantanderMetGroup/loadeR#28]
Hello,
I'm very new to this package and I want to use ISIMIP bias correction for temperature and precipitation. I was trying to get familiar with this package by following the commands given at 
https://github.com/SantanderMetGroup/loadeR/wiki/Accessing-and-loading-station-data
It was going well  then i got stuck with the following problem.

> example1 <- loadStationData(dataset = value,   var="tmax",  stationID = c("000234", "003946"),  season = 6:8,  years = 1981:2000)
Error in unzip(dataset, list = TRUE) : 
  zip file 'New folder/VALUE_ECA_86_v2' cannot be opened

For gridded data there was no problem and i was able to load it from the same directory.

Can someone guide me how i can solve this problem?
"New folder" is my working directory where i have download the data as explained in above give link.

Thank you!
Rizwan

**Comment by jbedia** [comment]
Hi Rizwan.
Thanks for your ticket. Some examples in the wiki are a bit outdated, sorry for that. The wiki is planned to be updated in the coming weeks/months with new case studies and updated examples. In this particular case, you should zip your target directory and point to the zip file in the argument dataset (in the new versions `loadStationData` will only work with zipped files).

**Comment by AZIZRIZWAN** [comment]
Thank you! I was able to load station data
