### ISSUE TITLE
Problem with loadStationData in new version

### ISSUE THREAD

**Issue by gcurci** [SantanderMetGroup/loadeR#29]
Hello,

I recently update the loadeR package, but I am experiencing a problem with loadStationData.

Following the example dataset:

download.file("http://meteo.unican.es/work/loadeR/data/VALUE_ECA_86_v2.tar.gz", destfile =  "VALUE_ECA_86_v2.tar.gz")
untar("VALUE_ECA_86_v2.tar.gz")
library(loadeR)
a = loadStationData("VALUE_ECA_86_v2")
Error in unzip(dataset, list = TRUE) : 
  zip file 'VALUE_ECA_86_v2' cannot be opened

Not sure why the code is looking for a zip file: is there something I am missing? It usually worked fine.

Thanks for any hint you may have on that, best wishes,
Gabriele

**Comment by miturbide** [comment]
Hi,

I am afraid the wiki is not fully updated (we are working on it).
The new version of loadStationData only considers zip files:

download.file("http://meteo.unican.es/work/loadeR/data/VALUE_ECA_86_v2.zip", destfile = "VALUE_ECA_86_v2.zip")
library(loadeR)
a = loadStationData("VALUE_ECA_86_v2.zip", var = "tmean")

**Comment by gcurci** [comment]
Hi, thanks much! I couldn't locate this info on the documentation. Now it works.

Best,
Gabriele
