### ISSUE TITLE
Could not able to locate function plotMeanfield

### ISSUE THREAD

**Issue by dhruv2207** [SantanderMetGroup/loadeR#32]
Hello, R is not able to find the function plotmeanfield, i checked the inventory for loadR, there also I was not able to find this function. Is there some other way to access it? 

Error in plotMeanField(tasmax) : could not find function "plotMeanField"

**Comment by miturbide** [comment]
Hello, plotMeanField has been replaced by spatialPlot in package visualizeR:

> devtools::install_github(c("SantanderMetGroup/transformeR", "SantanderMetGroup/visualizeR"))
> library(devtools)
> spatialPlot(climatology(tasmax))

**Comment by dhruv2207** [comment]
Thanks for the help and could you please also let me know where i can find Manuel for climate 4R, so that i can see the how the functions and packages can be implemented.

**Comment by miturbide** [comment]
There is a Wiki for each package of the climate4R bundle on gitHub. You could also check examples in the R help documentation to complement the Wiki examples (specially for the cases of non-updated code lines).

We plan to update the Wiki-s soon.

You can also check published papers: http://www.meteo.unican.es/climate4r
