### ISSUE TITLE
ERROR: dependency ‘loadeR.java’ is not available for package ‘loadeR’

### ISSUE THREAD

**Issue by suraj500** [SantanderMetGroup/loadeR#33]
Hi,
     I am trying to install loadeR on R 3.4 with Java 10 and rjava 9.10 on a mac 10.13.3.

I am gating following error: 

ERROR: dependency ‘loadeR.java’ is not available for package ‘loadeR’

any help to resolve the issue will be highly appreciated 

thanks in advance!
Suraj

**Comment by jbedia** [comment]
Dear Suraj, please have a look at the dedicated section in the [loadeR's wiki](https://github.com/SantanderMetGroup/loadeR/wiki/Installation). Also, in case you are using RStudio, please try to perform the installation outside it. I hope this helps.

**Comment by suraj500** [comment]
Dear Joaquin Bedia,
                           I followed all the instruction provided on
loadeR wiki, till I am gating similar error.


preparing package for lazy loading

Error: package or namespace load failed for ‘rJava’:

 .onLoad failed in loadNamespace() for 'rJava', details:

  call: dyn.load(file, DLLpath = DLLpath, ...)

  error: unable to load shared object
'/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':


dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so,
6): Library not loaded: @rpath/libjvm.dylib

  Referenced from:
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so

  Reason: image not found

Error : package ‘rJava’ could not be loaded

ERROR: lazy loading failed for package ‘loadeR.java’

* removing
‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/loadeR.java’

*Installation failed: Command failed (1)*

*Downloading GitHub repo SantanderMetGroup/loadeR@master*

*from URL
https://api.github.com/repos/SantanderMetGroup/loadeR/zipball/master
<https://api.github.com/repos/SantanderMetGroup/loadeR/zipball/master>*

*Installing loadeR*

*'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file
--no-environ  \*

*  --no-save --no-restore --quiet CMD INSTALL  \*

*
'/private/var/folders/df/95vp0cpx5jd0gdt7q6syg5mm0000gn/T/RtmpNiAnSB/devtoolsbcb82646835a/SantanderMetGroup-loadeR-e3bbc5c'
\*

*
--library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'
\*

*  --install-tests *


ERROR: dependency ‘loadeR.java’ is not available for package ‘loadeR’

* removing
‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/loadeR’

*Installation failed: Command failed (1)*


*Thanks for help!*

*Suraj*

**Comment by suraj500** [comment]
After updating I end up with this error

"devtools::install_github(c("SantanderMetGroup/loadeR.java", "SantanderMetGroup/loadeR"))

Downloading GitHub repo SantanderMetGroup/loadeR.java@master
from URL https://api.github.com/repos/SantanderMetGroup/loadeR.java/zipball/master
Installing loadeR.java
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rJava_0.9-9.tgz'
Content type 'application/x-gzip' length 626627 bytes (611 KB)
==================================================
downloaded 611 KB

Installing rJava
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/df/95vp0cpx5jd0gdt7q6syg5mm0000gn/T/RtmpRmL1uy/devtoolse53c2fbd043/rJava'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *binary* package ‘rJava’ ...
* DONE (rJava)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/df/95vp0cpx5jd0gdt7q6syg5mm0000gn/T/RtmpRmL1uy/devtoolse53c274ad168/SantanderMetGroup-loadeR.java-14fcdf1'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘loadeR.java’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning in fun(libname, pkgname) : NAs introduced by coercion
Error: package or namespace load failed for ‘loadeR.java’:
 .onAttach failed in attachNamespace() for 'loadeR.java', details:
  call: if (as.integer(substr(jversion, 3, 3)) < 7) {
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/loadeR.java’
Installation failed: Command failed (1)
Downloading GitHub repo SantanderMetGroup/loadeR@master
from URL https://api.github.com/repos/SantanderMetGroup/loadeR/zipball/master
Installing loadeR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/df/95vp0cpx5jd0gdt7q6syg5mm0000gn/T/RtmpRmL1uy/devtoolse53c30299656/SantanderMetGroup-loadeR-e3bbc5c'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

ERROR: dependency ‘loadeR.java’ is not available for package ‘loadeR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/loadeR’
Installation failed: Command failed (1)"

**Comment by jbedia** [comment]
Hi Suraj,
I suspect a problem related to Java10 , in the way it is recovering the version ([here](https://github.com/SantanderMetGroup/loadeR.java/blob/14fcdf1f29bad8166497689f9855be4cd751f274/R/onAttach.R#L2)). A new release of `loadeR.java` is about to appear. In the meantime, would it be possible for you to return to java 9 to see whether the problem persists or not? Thanks and sorry for the inconvenience

**Comment by cofinoa** [comment]
@jbedia using java9 it's not going to solve this. In java 9 a new version scheme has been introduce. 

See PR SantanderMetGroup/loadeR.java#2

**Comment by suraj500** [comment]
It seems like I need to wait for the new release of loadeR.java

**Comment by jbedia** [comment]
Hi Suraj. You can either wait for an update (possibly in a couple of weeks or so, but we can't guarantee), or switch back to version 8 when using `loadeR`, that is well tested and works fine. For the latter, you may find useful [this post](https://stackoverflow.com/a/44169445). Thanks for your feedback and sorry for this inconvenience.

**Comment by suraj500** [comment]
Thanks,
               It is working fine with Java8 but will be happy to have the new version which works with Java10.

**Comment by suraj500** [comment]
Thanks, much for the newer version of loadeR.java, it is working fine with Java 10
Thanks 
Suraj

**Comment by jbedia** [comment]
Great!
