### ISSUE TITLE
pseudo-bug when loading metadata from stations

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/loadeR#38]
Hi, 
I am using `climate4R` for statistical downscaling on a set of stations available as Excel files. I have created a piece of code to ``convert'' the data into the format needed to use loadStationData and I have realised that the function `loadStationData` in the following line:
```
 var.stids <- lapply(strsplit(readLines(unzcond(dataset, 
    zipFileContents[fileInd]), 1), split = ", "), FUN = trim)
```
does something potentially wrong because it's using `", "` to split the headers instead of `","`, so if you have a comma-separated file without spaces...it doesn't work! 

By the way, is this the only way to apply the `downscaleR` function to a set of time-series, is it possible to apply those functions to time-series stored in a simple `data.frame`?

**Comment by miturbide** [comment]
Thank you Matteo, I will fix it and let you know. 
downscale.train is a wrapper of internal functions that work with data.frames (such as glm.train).

**Comment by jbedia** [comment]
Hi Matteo, thanks for reporting. It seems like can be easily fixed by passing to the split argument an appropriate regular expression. @miturbide please, can you handle this? thanks to both

**Comment by miturbide** [comment]
Hi,
The `split` argument is now `","` (devel branch). Blank spaces (if any) are then controlled with function `trimws`.

**Comment by jbedia** [comment]
Thanks @miturbide , looks good (but didn't test it). @matteodefelice, can you please confirm before closing the issue?

**Comment by matteodefelice** [comment]
Yes, it seems to work! Thanks for fixing it!
