### ISSUE TITLE
Data field from loadStationData is a character array!

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/loadeR#40]
I was using successfully the function `loadStationData` to load each station contained in the following data directory: https://www.dropbox.com/s/b62o03gfiuk73ej/stations-data-cantabria.zip?dl=0

The code used was:
```
stn_c4r <- loadStationData("stations-data-cantabria/",
                             var = "precip", 
                             stationID = "NAME-OF-MY-STATION",
                             years = seq(2011, 2017))
```
In this way I had:
```
> str(stn_c4r$Data)
 num [1:2557, 1] 0.00208 0 0.00208 0.05 0.13542 ...
 - attr(*, "dimensions")= chr [1:2] "time" "loc"
```

I tried to load all the 9 stations together and I removed the parameter `stationID`:
```
stn_c4r <- loadStationData("stations-data-cantabria/",
                             var = "precip", 
                             years = seq(2011, 2017)
  )
```
but now:
```
> str(stn_c4r$Data)
 chr [1:2557, 1:9] "0.002083333" "0.000000000" "0.002083333" "0.050000000" "0.135416667" "0.160416667" ...
 - attr(*, "dimensions")= chr [1:2] "time" "loc"
```
Into `Data` I can only find characters! What happened here? Is the station data malformed?

**Comment by miturbide** [comment]
Hi Matteo,

The "missing_code" of your dataset is NaN (file variables.txt), however, precip.txt contains both NA and NaN for some stations (Porto, Seixo,  Sairrão.3). In these cases, when reading the file, NA values are interpreted as characters and when converting from data.frame to matrix, all values are transformed to characters.

It should work if you simply replace your NA values with NaN.

**Comment by matteodefelice** [comment]
great! Now it works! By the way it would be great if you suggest a way to transform tabular station data  (as what you get usually on a txt or csv file) into climate4r station data. Now I can close this, thank you again!
