### ISSUE TITLE
not able to access relative humidity

### ISSUE THREAD

**Issue by GeraldCNelson** [SantanderMetGroup/loadeR#57]
I'm try to download relative humidity data from this file and several others from the CMIP5 archive ` url <- http://meteo.unican.es/tds5/dodsC/cmip5/CCCMA/CANESM2/rcp85/day/cccma_canesm2_rcp85_r1i1p1.ncml`.

I have checked the data inventory and there is definitely a hur variable.

With var = "hur@10" and seas <- 1:12 I get this 

```
hur <- loadGridData(url, var = "hur@10",
+                          years = 2050, season = seas)
[2019-07-28 08:57:04] Opening dataset...
[2019-07-28 08:57:12] The dataset was successfuly opened
Error: Variable requested not found
Check 'dataInventory' output and/or dictionary 'identifier'.
```

With var = "hur" and seas <- 1:12 I get this

 ```
hur <- loadGridData(url, var = "hur",
+                          years = 2050, season = seas)
[2019-07-28 09:05:58] Opening dataset...
[2019-07-28 09:06:06] The dataset was successfuly opened
[2019-07-28 09:06:06] Defining geo-location parameters
[2019-07-28 09:06:07] Defining time selection parameters
Error in getVerticalLevelPars(grid, level) : 
  Variable with vertical levels: '@level' following the variable name is required
Possible values: 1000, 850, 700, 500, 250, 100, 50, 10
```

**Comment by omidnabavi** [comment]
Hi, 
Could you solve the problem?
Best,
Omid

**Comment by GeraldCNelson** [comment]
I haven't tried in quite some time. I've been working with the ISIMIP version of the CMIP6 data. It does have the hurs data available although at the moment they are fixing some problems with the bias correction.

**Comment by jbedia** [comment]
Hi @omidnabavi, the specified request works fine in my case. Please confirm that you working with an up-to-date package version.

**Comment by omidnabavi** [comment]
@jbedia As you suggested, updating the package solved the problem.

**Comment by jbedia** [comment]
Excellent, thanks for your prompt reply. I close this issue then. Best regards.
