### ISSUE TITLE
Error in .jnew(.class.to.jclass[cm], a) : java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiaoyujiaxyj** [SantanderMetGroup/loadeR#61]
Dear SantanderMetGroup,
I encountered some problems loading local data(.nc) from a dataset (.ncml). I failed to create the NcML file with function makeAggregatedDataset.
Here are the code:

makeAggregatedDataset(source.dir, ncml.file, file.ext = "nc", aggr.dim = "time")
[2019-12-04 09:51:22] Creating dataset from 190 files
[2019-12-04 09:51:27] Scanning file 1 out of 1
[2019-12-04 09:51:27] Defining aggregating dimension length
This process may be slow but will significantly speed-up data retrieval...
Error in .jnew(.class.to.jclass[cm], a) : java.lang.NullPointerException

I have emailed the data file to you and my email address is xiaoyujia18@mails.ucas.ac.cn.

Thank you in advance!

**Comment by cs2239** [comment]
I am getting this same error. Loading the files individually using loadGridData(dataset = ...,  var = ...) works fine, the makeAggregatedDataset throws the error:

[2021-04-13 10:18:19] Creating dataset from 2 files
[2021-04-13 10:18:19] Scanning file 1 out of 1
[2021-04-13 10:18:19] Defining aggregating dimension length
This process may be slow but will significantly speed-up data retrieval...
Error in .jnew(.class.to.jclass[cm], a) : java.lang.NullPointerException

**Comment by wombelejay** [comment]
@xiaoyujiaxyj I'm facing the same error .
how did you solve this ?
