### ISSUE TITLE
Could not access the opendap knmi 

### ISSUE THREAD

**Issue by pskunjeer** [SantanderMetGroup/loadeR#65]
As given in paper by Iturbide regarding climate data access and post-
processing, I could not access 

http://opendap.knmi.nl/knmi/thredds/dodsC/e-obs_0.25regular/tx_0.25deg_reg_v17.0.nc 

It gives error, that it is not valid URL and return status 502

**Comment by jbedia** [comment]
Hi, thanks for your question. It seems that the problem has nothing to do with loadeR... This is the message I get when trying to access the opendap server of the KNMI using my browser
![image](https://user-images.githubusercontent.com/5796721/80118579-e3ac7c80-8588-11ea-9e01-c30b6a466542.png)
I suggest to retrieve the data from the UDG:
```R
library(loadeR)
UDG.datasets(full.info = TRUE, pattern = "E-OBS")
``` 
I hope this helps
Best regards, Joaquín

**Comment by pskunjeer** [comment]
Thanks for reply, but could load tha data, error is 

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException: http://opendap.knmi.nl/knmi/thredds/dodsC/e-obs_0.25regular/tx_0.25deg_reg_v17.0.nc is not a valid URL, return status=502

**Comment by cofinoa** [comment]
@jbedia and @pskunjeer it's a problem on the KNMI side where data it's been published.

**Comment by cofinoa** [comment]
The KNMI opendap service it's back. 
@pskunjeer if you face problems again try to use @jbedia example:
```
library(loadeR)
UDG.datasets(full.info = TRUE, pattern = "E-OBS")
```
We store a "local" copy of KNMI data in our serve. 
Regards
